/**
 * Industry Factors Table Configuration
 * 
 * This configuration defines how the Industry Factor entity should be displayed
 * and edited using the ListDetailTemplate.
 * 
 * Based on Airtable "Industry Classification & Emission Factors" table.
 */

import { ListDetailTemplateConfig } from '../types'
import { industryClassificationApi } from '@/lib/api/industryClassification'
import type { IndustryClassification } from '@/lib/api/industryClassification'
import { autoGenerateFilters, mergeFilters } from '@/lib/autoGenerateFilters'
import { generateTableConfig, generateStatusColumn, generateAttachmentColumn } from '@/lib/templateGenerator'

// Create API client adapter
const industryClassificationApiClient = {
  getPaginated: async (params: {
    page?: number
    limit?: number
    search?: string
    sortBy?: string
    sortOrder?: 'asc' | 'desc'
    filters?: Record<string, any>
  }) => {
    const result = await industryClassificationApi.getPaginated({
      page: params.page || 1,
      limit: params.limit || 25,
      search: params.search,
      sortBy: params.sortBy,
      sortOrder: params.sortOrder,
      filters: params.filters,
    })
    return {
      data: result.data || [],
      pagination: {
        total: result.pagination?.total || 0,
        page: params.page || 1,
        limit: result.pagination?.limit || params.limit || 25,
        hasMore: result.pagination?.hasMore || false,
      },
    }
  },
  getById: async (id: string) => {
    return await industryClassificationApi.getById(id)
  },
  create: async (data: Partial<IndustryClassification>) => {
    return await industryClassificationApi.create(data as any)
  },
  update: async (id: string, data: Partial<IndustryClassification>) => {
    return await industryClassificationApi.update(id, data as any)
  },
  delete: async (id: string) => {
    await industryClassificationApi.delete(id)
  },
  getFilterValues: async (field: string, limit?: number) => {
    return await industryClassificationApi.getFilterValues(field, limit)
  },
}

// Define fields
const industryClassificationFields = [
  {
    key: 'Name',
    label: 'Name',
    type: 'text' as const,
    required: true,
    editable: true,
    section: 'general',
  },
  {
    key: 'Description',
    label: 'Description',
    type: 'textarea' as const,
    editable: true,
    section: 'general',
  },
  {
    key: 'Status',
    label: 'Status',
    type: 'select' as const,
    editable: true,
    options: async () => {
      return await industryClassificationApi.getFilterValues('Status', 100)
    },
    section: 'general',
  },
  {
    key: 'Attachment',
    label: 'Attachment',
    type: 'attachment' as const,
    editable: true,
    section: 'general',
  },
]

// Manual filters (can be overridden or extended)
const manualFilters = [
  {
    key: 'Status',
    label: 'Status',
    type: 'multiselect' as const, // Support multiple status selections
    options: async () => {
      return await industryClassificationApi.getFilterValues('Status', 100)
    },
    placeholder: 'All Status',
  },
]

// Auto-generate filters for non-text fields
const autoGeneratedFilters = autoGenerateFilters(industryClassificationFields, industryClassificationApiClient, manualFilters)

// Merge manual and auto-generated filters
const allFilters = mergeFilters(manualFilters, autoGeneratedFilters)

// Define columns
const industryClassificationColumns = [
  {
    key: 'Name',
    label: 'Name',
    sortable: true,
    align: 'left' as const,
    render: (value: string) => (
      <span className="text-sm font-medium text-neutral-900">
        {value || '—'}
      </span>
    ),
  },
  {
    key: 'Description',
    label: 'Description',
    sortable: false,
    align: 'left' as const,
    render: (value: string) => (
      <span className="text-sm text-neutral-600 line-clamp-2">
        {value || '—'}
      </span>
    ),
  },
  // Status column with color coding
  generateStatusColumn({
    key: 'Status',
    label: 'Status',
    statusColors: {
      'Active': { bg: 'bg-green-100', text: 'text-green-800' },
      'Inactive': { bg: 'bg-neutral-100', text: 'text-neutral-800' },
      'Submitted': { bg: 'bg-yellow-100', text: 'text-yellow-800' },
      'Draft': { bg: 'bg-blue-100', text: 'text-blue-800' },
      'Archived': { bg: 'bg-gray-100', text: 'text-gray-800' },
    },
    sortable: true,
    filterable: true,
  }),
  // Attachment column with thumbnails
  generateAttachmentColumn({
    key: 'Attachment',
    label: 'Attachment',
    maxThumbnails: 3,
  }),
]

// Generate configuration using template generator
export const industryClassificationConfig: ListDetailTemplateConfig<IndustryClassification> = generateTableConfig({
  entityName: 'Industry Factor',
  entityNamePlural: 'Industry Factors',
  description: 'Manage industry classification factors and categories. Define industry-specific emission factors and classification schemes for sector-based emission calculations.',
  fields: industryClassificationFields,
  columns: industryClassificationColumns,
  apiClient: industryClassificationApiClient,
  defaultSortField: 'Name',
  defaultSortOrder: 'asc',
  pageSizeOptions: [10, 25, 50, 100],
  showImportExport: true,
  panelTitleKey: 'Name',
  panelSections: [
    {
      id: 'general',
      title: 'General Information',
      fields: ['Name', 'Description', 'Status', 'Attachment'],
      collapsible: false,
    },
  ],
  manualFilters: allFilters,
  deleteConfirmMessage: 'Are you sure you want to delete this industry factor?',
})

