/**
 * User Roles Table Configuration
 * 
 * This configuration defines how the User Roles entity should be displayed
 * and edited using the ListDetailTemplate.
 * 
 * Based on Airtable "User Roles" table in System Configuration base.
 */

import { ListDetailTemplateConfig } from '../types'
import { userRolesApi } from '@/lib/api/userRoles'
import type { UserRole } from '@/lib/api/userRoles'
import { autoGenerateFilters, mergeFilters } from '@/lib/autoGenerateFilters'
import { generateTableConfig, generateStatusColumn } from '@/lib/templateGenerator'

// Create API client adapter
const userRolesApiClient = {
  getPaginated: async (params: {
    page?: number
    limit?: number
    search?: string
    sortBy?: string
    sortOrder?: 'asc' | 'desc'
    filters?: Record<string, any>
  }) => {
    const result = await userRolesApi.getPaginated({
      page: params.page || 1,
      limit: params.limit || 25,
      search: params.search,
      sortBy: params.sortBy,
      sortOrder: params.sortOrder,
      filters: params.filters,
    })
    return {
      data: result.data || [],
      pagination: {
        total: result.pagination?.total || 0,
        page: params.page || 1,
        limit: result.pagination?.limit || params.limit || 25,
        hasMore: result.pagination?.hasMore || false,
      },
    }
  },
  getById: async (id: string) => {
    return await userRolesApi.getById(id)
  },
  create: async (data: Partial<UserRole>) => {
    return await userRolesApi.create(data as any)
  },
  update: async (id: string, data: Partial<UserRole>) => {
    return await userRolesApi.update(id, data as any)
  },
  delete: async (id: string) => {
    await userRolesApi.delete(id)
  },
  getFilterValues: async (field: string, limit?: number) => {
    return await userRolesApi.getFilterValues(field, limit)
  },
}

// Define fields
const userRolesFields = [
  {
    key: 'Name',
    label: 'Name',
    type: 'text' as const,
    required: true,
    editable: true,
    section: 'general',
  },
  {
    key: 'Description',
    label: 'Description',
    type: 'textarea' as const,
    editable: true,
    section: 'general',
  },
]

// Manual filters (can be overridden or extended)
const manualFilters: any[] = []

// Auto-generate filters for non-text fields
const autoGeneratedFilters = autoGenerateFilters(userRolesFields, userRolesApiClient, manualFilters)

// Merge manual and auto-generated filters
const allFilters = mergeFilters(manualFilters, autoGeneratedFilters)

// Define columns
const userRolesColumns = [
  {
    key: 'Name',
    label: 'Name',
    sortable: true,
    align: 'left' as const,
    render: (value: string) => (
      <span className="text-sm font-medium text-neutral-900">
        {value || '—'}
      </span>
    ),
  },
  {
    key: 'Description',
    label: 'Description',
    sortable: false,
    align: 'left' as const,
    render: (value: string) => (
      <span className="text-sm text-neutral-600 line-clamp-2">
        {value || '—'}
      </span>
    ),
  },
]

// Generate configuration using template generator
export const userRolesConfig: ListDetailTemplateConfig<UserRole> = generateTableConfig({
  entityName: 'User Role',
  entityNamePlural: 'User Roles',
  fields: userRolesFields,
  columns: userRolesColumns,
  apiClient: userRolesApiClient,
  defaultSortField: 'Name',
  defaultSortOrder: 'asc',
  pageSizeOptions: [10, 25, 50, 100],
  showImportExport: true,
  panelTitleKey: 'Name',
  panelSections: [
    {
      id: 'general',
      title: 'General Information',
      fields: ['Name', 'Description'],
      collapsible: false,
    },
  ],
  manualFilters: allFilters,
  deleteConfirmMessage: 'Are you sure you want to delete this user role?',
})

